### ISSUE TITLE
Bug: Fix report header

### ISSUE THREAD

**Issue by anoop2811** [Guidewire/fern-reporter#45]
Currently the report header incorrectly is static and refers to ATMOS. It should be driven from config

**Comment by jjchambl** [comment]
I can take this one. Do we want this to be driven from an environment variable or something else? Also, would "Fern Acceptance Test Report" be a reasonable default?

**Comment by anoop2811** [comment]
I would think we should use config yaml as a the default and override using env variables. Yes, "Fern Acceptance Test Report" sounds like a reasonable default until someone comes up with a better default  :)

**Comment by tedd-E** [comment]
Closing after merge for PR #68
