### ISSUE TITLE
Chore: Move the fern client to its own repository

### ISSUE THREAD

**Issue by anoop2811** [Guidewire/fern-reporter#53]
Currently when a user imports the fern reporter client it downloads all the transitive dependencies of the server which are not required in the client. Move the client code to : github.com/Guidewire/fern-ginkgo-client

We could extend this pattern later to support other testing frameworks if possible like Junit etc if we can send the appropriate data

**Comment by mailprak** [comment]
PR to move the client code : 
https://github.com/Guidewire/fern-ginkgo-client/pull/1

**Comment by anoop2811** [comment]
Thanks for the PR and merged
